name: "refresh"

on:
  workflow_run:
    workflows: ["pages-build-deployment"]
    types: 
      - completed
  # 允许通过快捷指令/API触发
  repository_dispatch:
    types: [reset-debs]
  # 允许在 GitHub 网页手动点击触发
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # 修改条件：若是自动触发则检查上步状态，若是快捷指令/手动触发则直接运行
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive
          token: ${{ secrets.PAT_TOKEN }}  # 确保与 GitHub Secrets 中的名称一致
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

      # 【新增步骤】仅在快捷指令触发或网页手动触发时执行：清空 debs 并新建 README.md
      - name: Clean Debs Directory
        if: github.event_name == 'repository_dispatch' || github.event_name == 'workflow_dispatch'
        run: |
          rm -rf ./debs
          mkdir ./debs
          echo "# Debs Dir" > ./debs/README.md

      - name: Install Dependencies
        if: success()
        run: |
          sudo apt update -qq
          sudo apt install dpkg-dev bzip2 xz-utils zstd -y

      - name: Refresh Packages
        if: success()
        run: |
          rm -rf ./Packages*
          dpkg-scanpackages -m ./debs /dev/null >./Packages
          bzip2 -v -k -9 Packages
          xz -v -k -9 --extreme Packages
          zstd --ultra -22 -k Packages -o Packages.zst

      - name: Configure Git
        if: success()
        run: |
          git config --global user.email 'action@github.com'
          git config --global user.name 'GitHub Action'

      - name: Commit Changes
        if: success()
        run: |
          git add .
          if ! git diff --staged --exit-code 1>>/dev/null; then
            git commit -m 'Refresh Packages / Reset Debs'
          fi

      - name: Push Changes
        if: success() && github.ref == 'refs/heads/main'  # 确保在主分支上推送
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}  # 确保与 GitHub Secrets 中的名称一致
        run: |
          # 使用 PAT 进行身份验证
          git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git push origin main  # 根据实际分支名称修改，例如 main 或 master

      - name: Download remove_all_actions
        if: success()
        run: |
          sudo curl -L -o '/usr/bin/remove_all_actions' 'https://raw.githubusercontent.com/invalidunit/action/main/remove_all_actions'
          sudo chmod -R 0755 '/usr/bin/remove_all_actions'

      - name: Remove All Old Actions
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # 使用 PAT 替代默认的 GITHUB_TOKEN
          GH_REPO: ${{ github.repository }}
        run: |
          remove_all_actions
